language: php
sudo: false

php:
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4snapshot"

matrix:
  fast_finish: true
  include:
    - php: "7.0"
      env: CHECK_MBSTRING=1
    - php: "7.1"
      env: CHECK_MBSTRING=1
  allow_failures:
    - php: "master"
    - php: "7.4snapshot"

install:
  - composer self-update
  - composer update

script:
  - vendor/bin/phpunit
  - if [[ $CHECK_MBSTRING -eq 1 ]]; then php -dmbstring.func_overload=7 vendor/bin/phpunit; fi
  - vendor/bin/psalm
